runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:application
runtime_config:
  python_version: 3.6

env_variables:
  HOST: '0.0.0.0'
  FLASK_ENV: 'production'

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10